# Generated by Django 4.2.27 on 2026-03-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_knowledge_id_alter_testsession_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='test_type',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Moderate'), ('hard', 'Hard')], default='', max_length=10),
        ),
    ]
