# Generated by Django 4.2.27 on 2026-04-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_studentprofile_school_name_tutorprofile_fields_assessmenttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='looking_for_students',
            field=models.BooleanField(default=False),
        ),
    ]
