# Generated by Django 4.2.27 on 2026-04-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_remove_old_skill_template_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='edit_syllabus',
            field=models.BooleanField(default=False),
        ),
    ]
