# Generated by Django 4.2.27 on 2026-04-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_tutoring_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringsession',
            name='last_called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
