# Generated by Django 4.2.27 on 2026-04-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_tutoring_session_last_called_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
