# Generated by Django 4.2.27 on 2026-04-06 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_alter_user_role_distributorprofile_distributorparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfocusarea',
            name='learning_done_week',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfocusarea',
            name='tutoring_done_week',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='linked_focus_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_sessions', to='backend.studentfocusarea'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='mode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='testsession',
            name='mode_state',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='TestQuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.IntegerField()),
                ('skill_code', models.CharField(max_length=100)),
                ('correct', models.BooleanField()),
                ('time_taken_ms', models.IntegerField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='backend.testsession')),
            ],
            options={
                'ordering': ['answered_at'],
            },
        ),
    ]
