# Generated by Django 4.2.27 on 2026-04-06 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_studentfocusarea_learning_done_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTemplateProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.IntegerField()),
                ('skill_code', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=10)),
                ('ever_correct', models.BooleanField(default=False)),
                ('streak_start_date', models.DateField(blank=True, null=True)),
                ('has_robust', models.BooleanField(default=False)),
                ('last_answered_date', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'skill_code', 'difficulty'], name='backend_stu_student_a5fe9f_idx')],
                'unique_together': {('student', 'template_id')},
            },
        ),
        migrations.CreateModel(
            name='StudentSkillCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_competency', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'skill')},
            },
        ),
    ]
