# Generated by Django 4.2.27 on 2026-04-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_student_competency_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfocusarea',
            name='level_after_learning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfocusarea',
            name='level_before_learning',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
