# Generated by Django 4.2.27 on 2026-04-06 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_focus_area_learning_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='linked_tutoring_focus_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutoring_learning_sessions', to='backend.studentfocusarea'),
        ),
    ]
