# Generated by Django 4.2.27 on 2026-04-07 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_tutoring_fa_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('approve_distributor', 'Approve Distributor'), ('approve_tutor', 'Approve Tutor')], max_length=50)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['triggered_at'],
            },
        ),
    ]
