# Generated by Django 4.2.27 on 2026-04-08 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_adminjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorjob',
            name='show_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorjob',
            name='job_type',
            field=models.CharField(choices=[('send_progress_message', 'Send Progress Message'), ('review_focus_area', 'Review Focus Area'), ('review_available_hours', 'Review My Available Hours')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tutorjob',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='looking_for_students',
            field=models.BooleanField(default=True),
        ),
    ]
