# Generated by Django 4.2.27 on 2026-04-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_tutorjob_show_from_alter_tutorjob_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssendjob',
            name='to_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
