# Generated by Django 4.2.27 on 2026-04-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_add_to_number_to_smssend_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorjob',
            name='booking_ref',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
