# Generated by Django 4.2.27 on 2026-04-10 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_add_booking_ref_to_tutor_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('skill_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_groups', to='backend.skill')),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='backend.templategroup'),
        ),
    ]
