# Generated by Django 4.2.27 on 2026-04-15 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_templategroup_template_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_platform', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_distributor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_tutor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account_paid', models.CharField(blank=True, default='', max_length=255)),
                ('account_platform', models.CharField(blank=True, default='', max_length=255)),
                ('account_distributor', models.CharField(blank=True, default='', max_length=255)),
                ('account_tutor', models.CharField(blank=True, default='', max_length=255)),
                ('date_tuition', models.DateField(blank=True, help_text='Date the tuition session occurred', null=True)),
                ('date_debit', models.DateField(blank=True, help_text='Date the payment was debited from the payer', null=True)),
                ('date_credit', models.DateField(blank=True, help_text='Date the payment was credited to recipients', null=True)),
                ('focus_area', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_as_distributor', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_as_student', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_as_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_tuition', '-created_at'],
            },
        ),
    ]
