# Generated by Django 4.2.27 on 2026-04-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_payment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_details',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
