# Generated by Django 4.2.27 on 2026-04-17 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_bookingoutcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorjob',
            name='booking_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='backend.bookingoutcome'),
        ),
        migrations.AlterField(
            model_name='bookingoutcome',
            name='focus_areas',
            field=models.ManyToManyField(blank=True, help_text='Focus areas covered during this session.', related_name='booking_outcomes_current', to='backend.skill'),
        ),
        migrations.AlterField(
            model_name='bookingoutcome',
            name='focus_areas_next',
            field=models.ManyToManyField(blank=True, help_text='Focus areas for the next session. Same as focus_areas unless the tutor changes them.', related_name='booking_outcomes_next', to='backend.skill'),
        ),
    ]
