# Generated by Django 4.2.27 on 2026-04-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_tutorjob_booking_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=70, max_digits=8),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='default_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=70, max_digits=8),
        ),
    ]
