# Generated by Django 4.2.27 on 2026-04-17 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_tutoringsession_student_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='template',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='backend.template'),
        ),
    ]
