# Generated by Django 4.2.27 on 2026-04-19 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_template_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorjob',
            name='job_type',
            field=models.CharField(choices=[('post_tuition_review', 'Post Tuition Review'), ('send_progress_message', 'Send Progress Message'), ('review_focus_area', 'Review Focus Area'), ('review_available_hours', 'Review My Available Hours'), ('setup_weekly_session', 'Set Up Weekly Session')], max_length=50),
        ),
        migrations.CreateModel(
            name='WeeklyProgressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('post_session', 'Post Session'), ('scheduled', 'Scheduled')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
    ]
