# Generated by Django 4.2.27 on 2026-04-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_classassessment_skill_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='plain_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
