# Generated by Django 4.2.27 on 2026-05-06 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_grade_maxlen_year_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parentchild',
            name='sessions_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adminjob',
            name='job_type',
            field=models.CharField(choices=[('approve_distributor', 'Approve Distributor'), ('approve_tutor', 'Approve Tutor'), ('payment_failed', 'Payment Failed'), ('payment_overdue_7', 'Payment Overdue — 7 Days'), ('payment_overdue_14', 'Payment Overdue — 14 Days'), ('low_session_rating', 'Low Session Rating')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tutorjob',
            name='job_type',
            field=models.CharField(choices=[('post_tuition_review', 'Post Tuition Review'), ('send_progress_message', 'Send Progress Message'), ('review_focus_area', 'Review Focus Area'), ('review_available_hours', 'Review My Available Hours'), ('setup_weekly_session', 'Set Up Weekly Session'), ('payment_failed', 'Payment Failed'), ('payment_overdue_7', 'Payment Overdue — 7 Days'), ('payment_overdue_14', 'Payment Overdue — 14 Days — Sessions Paused')], max_length=50),
        ),
        migrations.CreateModel(
            name='SessionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('platform_amount', models.DecimalField(decimal_places=2, default=6.5, max_digits=8)),
                ('distributor_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authorised', 'Authorised'), ('paid', 'Paid'), ('failed', 'Failed'), ('overdue_7', 'Overdue 7d'), ('overdue_14', 'Overdue 14d')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorised_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expected_settlement_date', models.DateField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('rating_comment', models.TextField(blank=True, null=True)),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_payments_as_distributor', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_payments_as_parent', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_payment', to='backend.tutoringsession')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_payments_as_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentPaymentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('stripe_pm_id', models.CharField(blank=True, max_length=200, null=True)),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=20, null=True)),
                ('setup_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('payment_due', 'Payment Due'), ('payment_failed', 'Payment Failed — Update Card'), ('payment_overdue_7', 'Payment Overdue — 7 Days'), ('payment_overdue_14', 'Payment Overdue — Sessions Paused')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_jobs', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_jobs', to='backend.sessionpayment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
