# Generated by Django 4.2.27 on 2026-05-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_distributorprofile_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
