# Generated by Django 4.2.27 on 2026-05-22 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_studentprofile_min_questions_per_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionpayment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_payments_as_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionpayment',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_payment', to='backend.tutoringsession'),
        ),
        migrations.AlterField(
            model_name='tutorjob',
            name='job_type',
            field=models.CharField(choices=[('post_tuition_review', 'Post Tuition Review'), ('send_progress_message', 'Send Progress Message'), ('review_focus_area', 'Review Focus Area'), ('review_available_hours', 'Review My Available Hours'), ('setup_weekly_session', 'Set Up Weekly Session'), ('set_fee', 'Set Your Tutoring Fee'), ('payment_failed', 'Payment Failed'), ('payment_overdue_7', 'Payment Overdue — 7 Days'), ('payment_overdue_14', 'Payment Overdue — 14 Days — Sessions Paused')], max_length=50),
        ),
    ]
