# Generated by Django 4.2.27 on 2026-05-22 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_session_payment_nullable_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminjob',
            name='job_type',
            field=models.CharField(choices=[('approve_distributor', 'Approve Distributor'), ('approve_tutor', 'Approve Tutor'), ('payment_failed', 'Payment Failed'), ('payment_overdue_7', 'Payment Overdue — 7 Days'), ('payment_overdue_14', 'Payment Overdue — 14 Days'), ('low_session_rating', 'Low Session Rating'), ('setup_bank_details', 'Setup Bank Details')], max_length=50),
        ),
        migrations.AlterField(
            model_name='adminjob',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
