# Generated by Django 4.2.27 on 2026-05-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0065_admin_job_nullable_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionpayment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('authorised', 'Authorised'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('overdue_7', 'Overdue 7d'), ('overdue_14', 'Overdue 14d')], default='pending', max_length=20),
        ),
    ]
