# Generated by Django 4.2.27 on 2026-05-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0066_add_confirmed_status_to_session_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
