# Generated by Django 4.2.27 on 2026-05-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_studentprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminjob',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminjob',
            name='job_type',
            field=models.CharField(choices=[('approve_distributor', 'Approve Distributor'), ('approve_tutor', 'Approve Tutor'), ('payment_failed', 'Payment Failed'), ('payment_overdue_7', 'Payment Overdue — 7 Days'), ('payment_overdue_14', 'Payment Overdue — 14 Days'), ('low_session_rating', 'Low Session Rating'), ('setup_bank_details', 'Setup Bank Details'), ('tutor_removed', 'Tutor Removed')], max_length=50),
        ),
    ]
