# Generated by Django 4.2.27 on 2026-05-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_add_adminjob_notes_and_tutor_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorjob',
            name='job_type',
            field=models.CharField(choices=[('post_tuition_review', 'Post Tuition Review'), ('send_progress_message', 'Send Progress Message'), ('review_focus_area', 'Review Focus Area'), ('review_available_hours', 'Review My Available Hours'), ('setup_weekly_session', 'Set Up Weekly Session'), ('set_fee', 'Set Your Tutoring Fee'), ('payment_failed', 'Payment Failed'), ('payment_overdue_7', 'Payment Overdue — 7 Days'), ('payment_overdue_14', 'Payment Overdue — 14 Days — Sessions Paused'), ('confirm_payment_receipt', 'Confirm Payment Receipt')], max_length=50),
        ),
    ]
