# Generated by Django 4.2.27 on 2026-05-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0070_add_confirm_payment_receipt_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssendjob',
            name='message_type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
