# Generated by Django 4.2.27 on 2026-06-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0073_parent_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='assisted_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parentfeedback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
