web:    gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2
worker: celery -A config worker --loglevel=info
beat:   celery -A config beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=info
