# Generated by Django 4.0.4 on 2022-05-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_message_mobile_alter_message_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=200, null=True)),
                ('day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=200, null=True)),
                ('time', models.CharField(blank=True, choices=[('3:30pm', '3:30pm'), ('4:30pm', '4:30pm'), ('5:30pm', '5:30pm'), ('Other', 'Other')], max_length=200, null=True)),
                ('confirmed', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
