# Generated by Django 4.0.4 on 2022-05-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booking_message_alter_booking_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
