# Generated by Django 4.0.4 on 2022-05-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_booking_day_alter_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='day',
        ),
    ]
